# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x12\x64\x65\x65pface.api.proto\"\x94\x01\n\nFacialArea\x12\x10\n\x08left_eye\x18\x01 \x03(\r\x12\x11\n\tright_eye\x18\x02 \x03(\r\x12\x12\n\nmouth_left\x18\x03 \x03(\r\x12\x13\n\x0bmouth_right\x18\x04 \x03(\r\x12\x0c\n\x04nose\x18\x05 \x03(\r\x12\t\n\x01h\x18\x06 \x01(\r\x12\t\n\x01w\x18\x07 \x01(\r\x12\t\n\x01x\x18\x08 \x01(\r\x12\t\n\x01y\x18\t \x01(\r*\xa4\x01\n\x06Models\x12\x0c\n\x08VGG_FACE\x10\x00\x12\x0b\n\x07\x46\x41\x43\x45NET\x10\x01\x12\x0e\n\nFACENET512\x10\x02\x12\x0c\n\x08OPENFACE\x10\x03\x12\x0c\n\x08\x44\x45\x45PFACE\x10\x04\x12\n\n\x06\x44\x45\x45PID\x10\x05\x12\x0b\n\x07\x41RCFACE\x10\x06\x12\x0e\n\nDLIB_MODEL\x10\x07\x12\t\n\x05SFACE\x10\x08\x12\x10\n\x0cGHOSTFACENET\x10\t\x12\r\n\tBUFFALO_L\x10\n*\xb4\x01\n\tDetectors\x12\n\n\x06OPENCV\x10\x00\x12\x07\n\x03SSD\x10\x01\x12\x08\n\x04\x44LIB\x10\x02\x12\t\n\x05MTCNN\x10\x03\x12\r\n\tFASTMTCNN\x10\x04\x12\x0e\n\nRETINAFACE\x10\x05\x12\r\n\tMEDIAPIPE\x10\x06\x12\n\n\x06YOLOV8\x10\x07\x12\x0c\n\x08YOLOV11S\x10\x08\x12\x0c\n\x08YOLOV11N\x10\t\x12\x0c\n\x08YOLOV11M\x10\n\x12\t\n\x05YUNET\x10\x0b\x12\x0e\n\nCENTERFACE\x10\x0c*K\n\x0f\x44istanceMetrics\x12\n\n\x06\x43OSINE\x10\x00\x12\r\n\tEUCLIDEAN\x10\x01\x12\x10\n\x0c\x45UCLIDEAN_L2\x10\x02\x12\x0b\n\x07\x41NGULAR\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELS']._serialized_start=188
  _globals['_MODELS']._serialized_end=352
  _globals['_DETECTORS']._serialized_start=355
  _globals['_DETECTORS']._serialized_end=535
  _globals['_DISTANCEMETRICS']._serialized_start=537
  _globals['_DISTANCEMETRICS']._serialized_end=612
  _globals['_FACIALAREA']._serialized_start=37
  _globals['_FACIALAREA']._serialized_end=185
# @@protoc_insertion_point(module_scope)
