# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: represent.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'represent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frepresent.proto\x12\x12\x64\x65\x65pface.api.proto\x1a\x0c\x63ommon.proto\"\xe0\x02\n\x10RepresentRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x33\n\nmodel_name\x18\x02 \x01(\x0e\x32\x1a.deepface.api.proto.ModelsH\x00\x88\x01\x01\x12<\n\x10\x64\x65tector_backend\x18\x03 \x01(\x0e\x32\x1d.deepface.api.proto.DetectorsH\x01\x88\x01\x01\x12\x1e\n\x11\x65nforce_detection\x18\x04 \x01(\x08H\x02\x88\x01\x01\x12\x12\n\x05\x61lign\x18\x05 \x01(\x08H\x03\x88\x01\x01\x12\x1a\n\ranti_spoofing\x18\x06 \x01(\x08H\x04\x88\x01\x01\x12\x16\n\tmax_faces\x18\x07 \x01(\rH\x05\x88\x01\x01\x42\r\n\x0b_model_nameB\x13\n\x11_detector_backendB\x14\n\x12_enforce_detectionB\x08\n\x06_alignB\x10\n\x0e_anti_spoofingB\x0c\n\n_max_faces\"\xbf\x01\n\x11RepresentResponse\x12>\n\x07results\x18\x01 \x03(\x0b\x32-.deepface.api.proto.RepresentResponse.Results\x1aj\n\x07Results\x12\x11\n\tembedding\x18\x01 \x03(\x01\x12\x17\n\x0f\x66\x61\x63\x65_confidence\x18\x02 \x01(\x01\x12\x33\n\x0b\x66\x61\x63ial_area\x18\x03 \x01(\x0b\x32\x1e.deepface.api.proto.FacialArea2l\n\x10RepresentService\x12X\n\tRepresent\x12$.deepface.api.proto.RepresentRequest\x1a%.deepface.api.proto.RepresentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'represent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REPRESENTREQUEST']._serialized_start=54
  _globals['_REPRESENTREQUEST']._serialized_end=406
  _globals['_REPRESENTRESPONSE']._serialized_start=409
  _globals['_REPRESENTRESPONSE']._serialized_end=600
  _globals['_REPRESENTRESPONSE_RESULTS']._serialized_start=494
  _globals['_REPRESENTRESPONSE_RESULTS']._serialized_end=600
  _globals['_REPRESENTSERVICE']._serialized_start=602
  _globals['_REPRESENTSERVICE']._serialized_end=710
# @@protoc_insertion_point(module_scope)
