# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: verify.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'verify.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cverify.proto\x12\x12\x64\x65\x65pface.api.proto\x1a\x0c\x63ommon.proto\"\x9f\x03\n\rVerifyRequest\x12\x0e\n\x06image1\x18\x01 \x01(\x0c\x12\x0e\n\x06image2\x18\x02 \x01(\x0c\x12\x33\n\nmodel_name\x18\x03 \x01(\x0e\x32\x1a.deepface.api.proto.ModelsH\x00\x88\x01\x01\x12<\n\x10\x64\x65tector_backend\x18\x04 \x01(\x0e\x32\x1d.deepface.api.proto.DetectorsH\x01\x88\x01\x01\x12\x41\n\x0f\x64istance_metric\x18\x05 \x01(\x0e\x32#.deepface.api.proto.DistanceMetricsH\x02\x88\x01\x01\x12\x1e\n\x11\x65nforce_detection\x18\x06 \x01(\x08H\x03\x88\x01\x01\x12\x12\n\x05\x61lign\x18\x07 \x01(\x08H\x04\x88\x01\x01\x12\x1a\n\ranti_spoofing\x18\x08 \x01(\x08H\x05\x88\x01\x01\x42\r\n\x0b_model_nameB\x13\n\x11_detector_backendB\x12\n\x10_distance_metricB\x14\n\x12_enforce_detectionB\x08\n\x06_alignB\x10\n\x0e_anti_spoofing\"\xaa\x03\n\x0eVerifyResponse\x12\x10\n\x08verified\x18\x01 \x01(\x08\x12\x37\n\x10\x64\x65tector_backend\x18\x02 \x01(\x0e\x32\x1d.deepface.api.proto.Detectors\x12)\n\x05model\x18\x03 \x01(\x0e\x32\x1a.deepface.api.proto.Models\x12>\n\x11similarity_metric\x18\x04 \x01(\x0e\x32#.deepface.api.proto.DistanceMetrics\x12\x44\n\x0c\x66\x61\x63ial_areas\x18\x05 \x01(\x0b\x32..deepface.api.proto.VerifyResponse.FacialAreas\x12\x10\n\x08\x64istance\x18\x06 \x01(\x01\x12\x11\n\tthreshold\x18\x07 \x01(\x01\x12\x0c\n\x04time\x18\x08 \x01(\x01\x1ai\n\x0b\x46\x61\x63ialAreas\x12,\n\x04img1\x18\x01 \x01(\x0b\x32\x1e.deepface.api.proto.FacialArea\x12,\n\x04img2\x18\x02 \x01(\x0b\x32\x1e.deepface.api.proto.FacialArea2`\n\rVerifyService\x12O\n\x06Verify\x12!.deepface.api.proto.VerifyRequest\x1a\".deepface.api.proto.VerifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'verify_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERIFYREQUEST']._serialized_start=51
  _globals['_VERIFYREQUEST']._serialized_end=466
  _globals['_VERIFYRESPONSE']._serialized_start=469
  _globals['_VERIFYRESPONSE']._serialized_end=895
  _globals['_VERIFYRESPONSE_FACIALAREAS']._serialized_start=790
  _globals['_VERIFYRESPONSE_FACIALAREAS']._serialized_end=895
  _globals['_VERIFYSERVICE']._serialized_start=897
  _globals['_VERIFYSERVICE']._serialized_end=993
# @@protoc_insertion_point(module_scope)
