// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: represent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RepresentService_Represent_FullMethodName = "/deepface.api.proto.RepresentService/Represent"
)

// RepresentServiceClient is the client API for RepresentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RepresentServiceClient interface {
	Represent(ctx context.Context, in *RepresentRequest, opts ...grpc.CallOption) (*RepresentResponse, error)
}

type representServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRepresentServiceClient(cc grpc.ClientConnInterface) RepresentServiceClient {
	return &representServiceClient{cc}
}

func (c *representServiceClient) Represent(ctx context.Context, in *RepresentRequest, opts ...grpc.CallOption) (*RepresentResponse, error) {
	out := new(RepresentResponse)
	err := c.cc.Invoke(ctx, RepresentService_Represent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RepresentServiceServer is the server API for RepresentService service.
// All implementations must embed UnimplementedRepresentServiceServer
// for forward compatibility
type RepresentServiceServer interface {
	Represent(context.Context, *RepresentRequest) (*RepresentResponse, error)
	mustEmbedUnimplementedRepresentServiceServer()
}

// UnimplementedRepresentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRepresentServiceServer struct {
}

func (UnimplementedRepresentServiceServer) Represent(context.Context, *RepresentRequest) (*RepresentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Represent not implemented")
}
func (UnimplementedRepresentServiceServer) mustEmbedUnimplementedRepresentServiceServer() {}

// UnsafeRepresentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RepresentServiceServer will
// result in compilation errors.
type UnsafeRepresentServiceServer interface {
	mustEmbedUnimplementedRepresentServiceServer()
}

func RegisterRepresentServiceServer(s grpc.ServiceRegistrar, srv RepresentServiceServer) {
	s.RegisterService(&RepresentService_ServiceDesc, srv)
}

func _RepresentService_Represent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepresentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepresentServiceServer).Represent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepresentService_Represent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepresentServiceServer).Represent(ctx, req.(*RepresentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RepresentService_ServiceDesc is the grpc.ServiceDesc for RepresentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RepresentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deepface.api.proto.RepresentService",
	HandlerType: (*RepresentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Represent",
			Handler:    _RepresentService_Represent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "represent.proto",
}
